version: '3'

services:
    app:
        build:
            context: .
            dockerfile: DockerFile
        restart: always
        env_file:
            - ./.env
        volumes:
            - prisma-data:/app/prisma

volumes:
    prisma-data:
